///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VifurushiModalData {
/*
{
  "id": 1,
  "title": "Token 200",
  "description": "Jipatie Token 200 utakazoweza kupakua STORY uipendayo.",
  "price": "1000.00",
  "token_amount": 200
} 
*/

  int? id;
  String? title;
  String? description;
  String? price;
  int? tokenAmount;

  VifurushiModalData({
    this.id,
    this.title,
    this.description,
    this.price,
    this.tokenAmount,
  });
  VifurushiModalData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toString();
    tokenAmount = json['token_amount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['price'] = price;
    data['token_amount'] = tokenAmount;
    return data;
  }
}

class VifurushiModal {
/*
{
  "status": "success",
  "message": "Vifurushi fetched successfully",
  "status_code": 200,
  "data": [
    {
      "id": 1,
      "title": "Token 200",
      "description": "Jipatie Token 200 utakazoweza kupakua STORY uipendayo.",
      "price": "1000.00",
      "token_amount": 200
    }
  ]
} 
*/

  String? status;
  String? message;
  int? statusCode;
  List<VifurushiModalData?>? data;

  VifurushiModal({
    this.status,
    this.message,
    this.statusCode,
    this.data,
  });
  VifurushiModal.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <VifurushiModalData>[];
      v.forEach((v) {
        arr0.add(VifurushiModalData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['status_code'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
