///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideosModelData {
/*
{
  "id": 1,
  "video_title": "Unajua Kazi Ya Pipi Kifua? Ifahamu Namna Ya Kutumia Pipi Kifua Kwenye Mapenzi",
  "video_image": "https://kungwibucket.s3.amazonaws.com/videos/images/lavidavi.jpeg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=8jG6r2C576RAdrL0EhTwB0GuIBI%3D&Expires=1703943960",
  "video_url": "https://kungwibucket.s3.amazonaws.com/videosupload/videoplayback.mp4",
  "is_trending": true,
  "video_description": "pipi kifua tropical"
} 
*/

  int? id;
  String? videoTitle;
  String? videoImage;
  String? videoUrl;
  bool? isTrending;
  String? videoDescription;

  VideosModelData({
    this.id,
    this.videoTitle,
    this.videoImage,
    this.videoUrl,
    this.isTrending,
    this.videoDescription,
  });
  VideosModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    videoTitle = json['video_title']?.toString();
    videoImage = json['video_image']?.toString();
    videoUrl = json['video_url']?.toString();
    isTrending = json['is_trending'];
    videoDescription = json['video_description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['video_title'] = videoTitle;
    data['video_image'] = videoImage;
    data['video_url'] = videoUrl;
    data['is_trending'] = isTrending;
    data['video_description'] = videoDescription;
    return data;
  }
}

class VideosModel {
/*
{
  "status": "success",
  "message": "Trending Videos pulled successfully",
  "data": [
    {
      "id": 1,
      "video_title": "Unajua Kazi Ya Pipi Kifua? Ifahamu Namna Ya Kutumia Pipi Kifua Kwenye Mapenzi",
      "video_image": "https://kungwibucket.s3.amazonaws.com/videos/images/lavidavi.jpeg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=8jG6r2C576RAdrL0EhTwB0GuIBI%3D&Expires=1703943960",
      "video_url": "https://kungwibucket.s3.amazonaws.com/videosupload/videoplayback.mp4",
      "is_trending": true,
      "video_description": "pipi kifua tropical"
    }
  ],
  "status_code": 200
} 
*/

  String? status;
  String? message;
  List<VideosModelData?>? data;
  int? statusCode;

  VideosModel({
    this.status,
    this.message,
    this.data,
    this.statusCode,
  });
  VideosModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <VideosModelData>[];
      v.forEach((v) {
        arr0.add(VideosModelData.fromJson(v));
      });
      data = arr0;
    }
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    data['status_code'] = statusCode;
    return data;
  }
}
