///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SeriesModelDataSeriesEpisodes {
/*
{
  "id": 1,
  "episode_title": "Unajua Kazi Ya Pipi Kifua? Ifahamu Namna Ya Kutumia Pipi Kifua Kwenye Mapenzi",
  "episode_image": "https://kungwibucket.s3.amazonaws.com/episodes/images/sddefault.jpg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=naMXAtv4YoJmI%2Bvu8iaMjHV5wfY%3D&Expires=1703944112",
  "episode_url": "https://kungwibucket.s3.amazonaws.com/videosupload/videoplayback.mp4",
  "episode_description": "pipi kifua",
  "series": 1
} 
*/

  int? id;
  String? episodeTitle;
  String? episodeImage;
  String? episodeUrl;
  String? episodeDescription;
  int? series;

  SeriesModelDataSeriesEpisodes({
    this.id,
    this.episodeTitle,
    this.episodeImage,
    this.episodeUrl,
    this.episodeDescription,
    this.series,
  });
  SeriesModelDataSeriesEpisodes.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    episodeTitle = json['episode_title']?.toString();
    episodeImage = json['episode_image']?.toString();
    episodeUrl = json['episode_url']?.toString();
    episodeDescription = json['episode_description']?.toString();
    series = json['series']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['episode_title'] = episodeTitle;
    data['episode_image'] = episodeImage;
    data['episode_url'] = episodeUrl;
    data['episode_description'] = episodeDescription;
    data['series'] = series;
    return data;
  }
}

class SeriesModelData {
/*
{
  "id": 1,
  "series_episodes": [
    {
      "id": 1,
      "episode_title": "Unajua Kazi Ya Pipi Kifua? Ifahamu Namna Ya Kutumia Pipi Kifua Kwenye Mapenzi",
      "episode_image": "https://kungwibucket.s3.amazonaws.com/episodes/images/sddefault.jpg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=naMXAtv4YoJmI%2Bvu8iaMjHV5wfY%3D&Expires=1703944112",
      "episode_url": "https://kungwibucket.s3.amazonaws.com/videosupload/videoplayback.mp4",
      "episode_description": "pipi kifua",
      "series": 1
    }
  ],
  "video_title": "Kungwi Series",
  "series_image": "https://kungwibucket.s3.amazonaws.com/series/images/lavidavi.jpeg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=Q4VWZCOQA2SCHqkVefhI%2BYS4Bmw%3D&Expires=1703944112",
  "is_trending": true,
  "series_description": "mfululizo wa kipekee uliotengenezwa mahususi kwa ajili ya kuwaelimisha wanawake kuhusu afya na elimu ya jinsia. Ikiwa imeandaliwa na fundi kungwi mwenye uzoefu na utaalamu mkubwa, series hii inalenga kutoa mwongozo, maarifa, na uelewa wa masuala ya kijinsia katika lugha nyepesi na ya kueleweka ya Kiswahili. Kila kipindi kinachambua mada mbalimbali zinazohusu afya ya uzazi, usalama katika mahusiano, na umuhimu wa kujitambua kijinsia, huku kikijikita katika kujenga mazingira ya wazi na ya kuheshimiana ambapo wanawake wanaweza kujifunza na kuuliza maswali bila woga."
} 
*/

  int? id;
  List<SeriesModelDataSeriesEpisodes?>? seriesEpisodes;
  String? videoTitle;
  String? seriesImage;
  bool? isTrending;
  String? seriesDescription;

  SeriesModelData({
    this.id,
    this.seriesEpisodes,
    this.videoTitle,
    this.seriesImage,
    this.isTrending,
    this.seriesDescription,
  });
  SeriesModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    if (json['series_episodes'] != null) {
      final v = json['series_episodes'];
      final arr0 = <SeriesModelDataSeriesEpisodes>[];
      v.forEach((v) {
        arr0.add(SeriesModelDataSeriesEpisodes.fromJson(v));
      });
      seriesEpisodes = arr0;
    }
    videoTitle = json['video_title']?.toString();
    seriesImage = json['series_image']?.toString();
    isTrending = json['is_trending'];
    seriesDescription = json['series_description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (seriesEpisodes != null) {
      final v = seriesEpisodes;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['series_episodes'] = arr0;
    }
    data['video_title'] = videoTitle;
    data['series_image'] = seriesImage;
    data['is_trending'] = isTrending;
    data['series_description'] = seriesDescription;
    return data;
  }
}

class SeriesModel {
/*
{
  "status": "success",
  "message": "Trending Series pulled successfully",
  "data": [
    {
      "id": 1,
      "series_episodes": [
        {
          "id": 1,
          "episode_title": "Unajua Kazi Ya Pipi Kifua? Ifahamu Namna Ya Kutumia Pipi Kifua Kwenye Mapenzi",
          "episode_image": "https://kungwibucket.s3.amazonaws.com/episodes/images/sddefault.jpg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=naMXAtv4YoJmI%2Bvu8iaMjHV5wfY%3D&Expires=1703944112",
          "episode_url": "https://kungwibucket.s3.amazonaws.com/videosupload/videoplayback.mp4",
          "episode_description": "pipi kifua",
          "series": 1
        }
      ],
      "video_title": "Kungwi Series",
      "series_image": "https://kungwibucket.s3.amazonaws.com/series/images/lavidavi.jpeg?AWSAccessKeyId=AKIATA2VV6MVQCJU2W5H&Signature=Q4VWZCOQA2SCHqkVefhI%2BYS4Bmw%3D&Expires=1703944112",
      "is_trending": true,
      "series_description": "mfululizo wa kipekee uliotengenezwa mahususi kwa ajili ya kuwaelimisha wanawake kuhusu afya na elimu ya jinsia. Ikiwa imeandaliwa na fundi kungwi mwenye uzoefu na utaalamu mkubwa, series hii inalenga kutoa mwongozo, maarifa, na uelewa wa masuala ya kijinsia katika lugha nyepesi na ya kueleweka ya Kiswahili. Kila kipindi kinachambua mada mbalimbali zinazohusu afya ya uzazi, usalama katika mahusiano, na umuhimu wa kujitambua kijinsia, huku kikijikita katika kujenga mazingira ya wazi na ya kuheshimiana ambapo wanawake wanaweza kujifunza na kuuliza maswali bila woga."
    }
  ],
  "status_code": 200
} 
*/

  String? status;
  String? message;
  List<SeriesModelData?>? data;
  int? statusCode;

  SeriesModel({
    this.status,
    this.message,
    this.data,
    this.statusCode,
  });
  SeriesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SeriesModelData>[];
      v.forEach((v) {
        arr0.add(SeriesModelData.fromJson(v));
      });
      data = arr0;
    }
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    data['status_code'] = statusCode;
    return data;
  }
}
